### ISSUE TITLE
Akka Discovery for Lagom

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#19] opened 2018-11-29 08:10 UTC
Here is a short TODO list of things I believe should be done in order to support Akka discovery for Lagom and Play.

Relates to #14

- [ ] Guice module should be able, via property, to wire production ServiceLocator
- [ ] if akka-discovery is configured, we should wire ServiceLocator bridge by default (Java)
- [ ] Scala component to provide prod ServiceLocator (@jroper is preparing a PR for this)
- [ ] Lagom client should be able, via property, to use ServiceDiscovery directly
- [ ] Akka Cluster Bootstrap as default bootstrap mechanisms in Lagom
- [ ] improve configuration, per service
- [ ] explore how we can use additional routers to include akka-mngt-http and health check (relates to https://github.com/lightbend/play-lagom-team/issues/14#issuecomment-442671852)
- [ ]  Health check - move it from reactive-lib to akka-management (in progress by Akka Team)

**Comment by dwijnand** [comment] 2019-02-14 07:49
Duplicate of lagom/lagom#1291

**Closed by dwijnand** 2019-02-14 07:49 UTC
